backend:
  name: git-gateway
media_folder: static/img
public_folder: img
collections:
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - file: data/settings/main_menu.yml
        label: Header Menu
        name: main_menu
        fields:
          - label: Nav items
            name: nav_items
            widget: list
            fields:
              - label: Label
                name: label
                widget: string
              - label: Path
                name: path
                widget: string
          - label: Header CTA Button text
            name: header_cta_button_text
            widget: string
          - label: Header CTA Button url
            name: header_cta_button_url
            widget: string
      - file: data/settings/footer_menu.yml
        label: Footer menu
        name: footer_menu
        fields:
          - label: Nav items
            name: nav_items
            widget: list
            fields:
              - label: Label
                name: label
                widget: string
              - label: Path
                name: path
                widget: string
      - file: data/settings/socials.yml
        label: Socials icon
        name: socials
        fields:
          - label: Nav items
            name: nav_items
            widget: list
            fields:
              - label: Icon
                name: icon
                widget: markdown
              - label: Icon URL
                name: icon_url
                widget: string
          - label: Copyright
            name: copyright
            widget: string
  - name: blog
    label: Blog
    folder: content/blog
    editor:
      preview: false
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Thumbnail
        name: thumbnail
        widget: image
      - label: Body
        name: body
        widget: markdown

  - name: page
    label: Page
    editor:
      preview: false
    files:
      - file: content/_index.md
        label: Home Page
        name: home
        fields:
          - label: Title
            name: title
            widget: string

          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Upline
                name: upline
                widget: string
                required: false
              - label: Title
                name: title
                widget: string
              - label: Intro image
                name: image
                widget: image
              - label: Button URL
                name: btn_url
                widget: string                
              - label: Button text
                name: btn_text
                widget: string   

          - label: About Us
            name: about_us
            widget: object
            fields:
              - label: Box
                name: box
                widget: list                
                fields:
                  - label: Number
                    name: number
                    widget: string                   
                  - label: Icon
                    name: icon
                    widget: image
                  - label: Text
                    name: text
                    widget: string                    
              - label: Title
                name: title
                widget: string
              - label: Achievements
                name: achievements
                widget: list                
                fields:
                  - label: Number
                    name: number
                    widget: string                   
                  - label: Text
                    name: text
                    widget: string
              - label: Info
                name: info
                widget: string 

          - label: Partners
            name: partners
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Partners
                name: box
                widget: list                
                fields:
                  - label: Image
                    name: image
                    widget: image 

          - label: Team
            name: team
            widget: object
            fields:             
              - label: Title
                name: title
                widget: string
              - label: Team Box
                name: box
                widget: list                
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Name
                    name: name
                    widget: string
                  - label: Position
                    name: position
                    widget: string
          - label: Slider
            name: reviews
            widget: object
            fields:
              - label: Upline
                name: upline
                widget: string
                required: false
              - label: Title
                name: title
                widget: string
              - label: Slider
                name: slider
                widget: list                
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Text
                    name: text
                    widget: string
                  - label: Name
                    name: name
                    widget: string
                  - label: Position
                    name: position
                    widget: string                                 
          - label: Form
            name: form
            widget: object
            fields:  
              - label: Upline
                name: uptitle
                widget: string
                required: false
              - label: Title
                name: title
                widget: string  
              - label: Text
                name: text
                widget: string 
              - label: Mail
                name: mail
                widget: string 
              - label: First name
                name: first_name
                widget: string 
              - label: Last Name
                name: last_name
                widget: string 
              - label: Telegram
                name: telegram
                widget: string 
              - label: Message
                name: message
                widget: string
              - label: Button Text
                name: btn_text
                widget: string 
              


